name: '5.internal-document-search-deployment'

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Login azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          enable-AzPSSession: true
      
      - name: Set up Azure PowerShell
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $ENV:SUB = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            $ENV:AZURE_PRINCEPAL_ID = az ad user show --id $ENV:USER_ID -o tsv --query id
          azPSVersion: "latest"
  
  deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: test az login status
        run: az account show

      - name: check powershell env
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $ENV:SUB
          azPSVersion: "latest"
      
